package resolve

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The fixtures under testdata/reconcile are the specification, and this reads
// them rather than restating them (prov-2026-4c49ca46).
//
// Restating would let the two drift, and the corpus is where the reasoning
// lives: every case carries the decision it records, and every input is real -
// generated by Sedum, or by the target stack's own generator. A case added
// there is covered here without anyone remembering to add it.

const corpusDir = "../../testdata/reconcile"

type corpusCase struct {
	Name          string `json:"name"`
	CommentPrefix string `json:"comment_prefix"`
	Language      string `json:"language"`
	Outcome       string `json:"outcome"`
	Diagnostic    string `json:"diagnostic"`
	Why           string `json:"why"`
}

func loadCorpus(t *testing.T) []corpusCase {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(corpusDir, "cases.json"))
	if err != nil {
		t.Fatalf("reading the reconciliation corpus: %v", err)
	}
	var corpus struct {
		Cases []corpusCase `json:"cases"`
	}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("the reconciliation corpus is not valid JSON: %v", err)
	}
	if len(corpus.Cases) == 0 {
		t.Fatal("the reconciliation corpus carries no cases")
	}
	return corpus.Cases
}

func read(t *testing.T, name, file string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(corpusDir, "cases", name, file))
	if err != nil {
		t.Fatalf("case %s: %v", name, err)
	}
	return string(data)
}

func TestReconciliationCorpus(t *testing.T) {
	for _, tc := range loadCorpus(t) {
		t.Run(tc.Name, func(t *testing.T) {
			if tc.Why == "" || tc.CommentPrefix == "" {
				t.Fatal("case records no reasoning or no comment prefix")
			}

			existing := read(t, tc.Name, "template")
			got, err := reconcile(tc.CommentPrefix, tc.Name, "the template",
				read(t, tc.Name, "existing"), existing)

			if tc.Outcome == "halt" {
				if err == nil {
					t.Fatalf("expected a halt, got:\n%s", got.Content)
				}
				if !strings.Contains(err.Error(), tc.Diagnostic) {
					t.Errorf("halt does not carry %q:\n%v", tc.Diagnostic, err)
				}
				return
			}

			if err != nil {
				t.Fatalf("expected this to apply: %v", err)
			}
			want := read(t, tc.Name, "expected")
			if got.Content != want {
				t.Errorf("reconciled to\n%s\nwant\n%s", got.Content, want)
			}
			if tc.Outcome == "unchanged" && got.Inserted != 0 {
				t.Errorf("a file that matches its template reported %d inserted line(s)", got.Inserted)
			}
			if tc.Outcome == "apply" && got.Inserted == 0 {
				t.Error("a file the template adds to reported nothing inserted")
			}
		})
	}
}

// Every case in the corpus must be exercised. A case added to the data and not
// reached here would look like coverage and be none.
func TestReconciliationCorpusIsFullyExercised(t *testing.T) {
	entries, err := os.ReadDir(filepath.Join(corpusDir, "cases"))
	if err != nil {
		t.Fatalf("reading the corpus: %v", err)
	}

	declared := map[string]bool{}
	for _, tc := range loadCorpus(t) {
		declared[tc.Name] = true
	}
	for _, e := range entries {
		if e.IsDir() && !declared[e.Name()] {
			t.Errorf("case directory %s is not declared in cases.json, so nothing runs it", e.Name())
		}
	}
}

// The corpus is deliberately not all one language, because the rule is not
// allowed to know one. Three prefixes today; a fourth needs a case and nothing
// else.
func TestReconciliationIsProvedAcrossCommentPrefixes(t *testing.T) {
	prefixes := map[string]bool{}
	for _, tc := range loadCorpus(t) {
		prefixes[tc.CommentPrefix] = true
	}
	if len(prefixes) < 3 {
		t.Errorf("the corpus covers %d comment prefix(es); the no-target-knowledge claim needs more than one to mean anything", len(prefixes))
	}
}
